### ISSUE TITLE
[ERROR] java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by wakatel** [xGinko/NeroChat#52]
Error occurred while enabling NeroChat v2.1 (Is it up to date?)
java.lang.NoSuchMethodError: org.yaml.snakeyaml.representer.Representer: method 'void <init>()' not found
        at io.github.thatsmusic99.configurationmaster.api.ConfigFile.<init>(ConfigFile.java:45) ~[NeroChat-2.1.jar:?]
        at io.github.thatsmusic99.configurationmaster.api.ConfigFile.loadConfig(ConfigFile.java:102) ~[NeroChat-2.1.jar:?]
        at me.softik.nerochat.utils.ConfigCache.loadConfig(ConfigCache.java:158) ~[NeroChat-2.1.jar:?]
        at me.softik.nerochat.utils.ConfigCache.<init>(ConfigCache.java:76) ~[NeroChat-2.1.jar:?]
        at me.softik.nerochat.NeroChat.reloadNeroChat(NeroChat.java:142) ~[NeroChat-2.1.jar:?]
        at me.softik.nerochat.NeroChat.onEnable(NeroChat.java:74) ~[NeroChat-2.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[folia-1.20.4.jar:git-Folia-"8210085"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[folia-1.20.4.jar:git-Folia-"8210085"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:645) ~[folia-1.20.4.jar:git-Folia-"8210085"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:556) ~[folia-1.20.4.jar:git-Folia-"8210085"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:713) ~[folia-1.20.4.jar:git-Folia-"8210085"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:458) ~[folia-1.20.4.jar:git-Folia-"8210085"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[folia-1.20.4.jar:git-Folia-"8210085"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[folia-1.20.4.jar:git-Folia-"8210085"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346) ~[folia-1.20.4.jar:git-Folia-"8210085"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by xKumorio** [comment]
https://github.com/xGinko/NeroChat/actions/runs/9333171332
You seem to be using an older version, try this
